// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

interface ISUSDE is IERC20 {
    function convertToShares(uint256 assets) external view returns (uint256);

    function cooldownShares(uint256 shares) external returns (uint256 assets);

    function deposit(uint256 assets, address receiver) external returns (uint256);

    function mint(uint256 shares, address receiver) external returns (uint256);

    function previewRedeem(uint256 shares) external view returns (uint256);

    function unstake(address receiver) external;
}
